#!/bin/usr/env ruby

require_relative '../lib/mes_courses/deployment'
include MesCourses::Deployment

with_trace_argument "create an heroku app with the corresponding git remote", (proc do
  opt :repo, "name of the remote git repo, the corresponding app should be named mes-courses-<repo> by convention", required: true, type: :string
                                                                                 opt :api_key, "heroku api key", required: true, type: :string
                                                                                 opt :sql_db_plan, "sql db plan", type: :string, default: "dev"
                                                                                 opt :ssl, "ssl endpoint"

end) do |options|

  create_heroku_app options[:repo], options[:api_key], options[:sql_db_plan], options[:ssl]
end
