#!/bin/usr/env ruby

require_relative '../lib/mes_courses/deployment'
include MesCourses::Deployment

with_repo_argument("create_heroku_app", "create an heroku app with the corresponding git remote") do |repo|
  create_heroku_app(repo)
end
