#!/bin/usr/env ruby

require_relative '../lib/deployment'
include Deployment

with_help_support("integrate", "Integrates the latest developments to the main repository, deploys to test and integration heroku applications") do
  with_confirmation("integrate the latest developments") do
    with_timing do
      puts "\nPulling latest developments"
      pull "dev"

      shell "ruby #{File.join(File.dirname(__FILE__), '..', 'lib', 'boot')}"
    end
  end
end
