#!/bin/usr/env ruby

require_relative '../lib/mes_courses/deployment'
include MesCourses::Deployment

with_trace_argument "Integrates the latest developments to the main repository, deploys to test and integration heroku applications" do
  with_confirmation("integrate the latest developments") do
    with_timing do

      # pull first, and then start a new process to integrate with latest scripts

      puts "\nPulling latest developments"
      pull "dev"

      shell "ruby #{File.join(File.dirname(__FILE__), '..', 'lib', 'mes_courses', 'deployment', 'end_integrate.rb')}"
    end
  end
end
