#!/bin/usr/env ruby

require_relative '../lib/mes_courses/deployment'
include MesCourses::Deployment

with_trace_argument "print_test_and_integration_apps", "prints the names of all test and integration apps" do
  test_and_integration_repos.each do |repo|
    puts heroku_app(repo)
  end
end
