#!/bin/usr/env ruby

require_relative '../lib/deployment'
include Deployment

with_repo_argument("raw_deploy", "Immediately deploys master branch to the specified remote heroku repo, without any confirmation !") do |repo|
  raw_deploy(repo)
end
