#!/bin/sh

## pre requirements
echo "You should already have a dev env on this machine"

## installing gems
bundle install

## post requirements
echo "create a terminal shortcut to this directory with a different background color"

