#!/bin/sh

## packages dependencies
# TODO insert these packages in the Gemfile somewhere (comments or special function) and get them later on
sudo apt-get install libxml2-dev libxslt1-dev postgresql libpq-dev sqlite3 libsqlite3-dev
sudo npm install -g csslint

## installing gems
bundle install
rbenv rehash

## creating dbs
sudo -u postgres createuser --superuser mes_courses
sudo -u postgres psql --command="alter user mes_courses with encrypted password 'password'"
sudo sed -i 's/\(local *all *all *\)peer/\1md5/' /etc/postgresql/9.1/main/pg_hba.conf
bundle exec rake db:create:all

## initializing dbs
bundle exec rake db:migrate
RAILS_ENV=cucumber bundle exec rake db:migrate
RAILS_ENV=ci bundle exec rake db:migrate
RAILS_ENV=production bundle exec rake db:migrate

## initializing config vars
cd config
ln -s /home/philou/BoxCryptor/mes-courses.fr/local_env.yml .
